# Generated by Django 6.0 on 2026-01-02 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='name',
            new_name='title',
        ),
    ]
